### ISSUE TITLE
getCovarianceMatrix always returns singular matrix

### ISSUE THREAD

**Issue by search4mahesh** [HGGM-LIM/jclustering#12]
Hi,

Why does getCovarianceMatrix always returns singular matrix with determinant as 0.

Thanks,
Mahesh

**Comment by rinze** [comment]
I would need a sample of your data to check this. That function is used directly from the Apache Common Math libraries. In principle, that would mean you have highly correlated data, but that is only speculation.

**Comment by rinze** [comment]
No feedback, closing.
