### ISSUE TITLE
DBSCAN

### ISSUE THREAD

**Issue by jmmateoshggm** [HGGM-LIM/jclustering#6]
Implement http://en.wikipedia.org/wiki/DBSCAN

Consider, however, that according to Philipp K. Janert, that implementation might be wrong. 

There is a Java implementation that can be used as reference or included directly (if the license allows it) at https://code.google.com/p/cluster-algorithms-java-alpha/source/browse/trunk/Clusterer/src/algorithms/DBSCAN.java

**Comment by jmmateoshggm** [comment]
May adapt the Apache Commons Math code: 

http://svn.apache.org/viewvc/commons/proper/math/trunk/src/main/java/org/apache/commons/math3/ml/clustering/DBSCANClusterer.java?view=markup

**Comment by rinze** [comment]
WONTFIX.
